[package]
name = "rust_ml"
version = "0.1.0"
authors = ["Philipp <pengelmann92@googlemail.com>"]

[lib]
name = "linear_regression"
path = "src/lib.rs"

[dependencies]
rustplot = "0.1.0"
plotlib = "0.3.0"